// Package fix generates corrected well-known artifacts for --fix. It never
// performs network I/O: everything here is pure text generation from
// already-fetched content (or a bare host name when nothing was fetched),
// printed to stdout for the caller to review and publish by hand.
package fix

import (
	"fmt"
	"strings"
	"time"

	"github.com/harborproject/magpie/internal/validate"
)

// OneYear is the validity window a freshly generated Expires field uses,
// matching RFC 9116's recommended maximum.
const OneYear = 365 * 24 * time.Hour

// SecurityTxt renders a complete, RFC 9116 compliant security.txt for host.
// existingBody is the previously fetched file's content, if any (nil or
// empty when security.txt was missing or unparseable); values found in it
// are reused, and anything magpie couldn't discover is called out with a
// "# TODO" comment immediately above the field it concerns, or in place of
// the field entirely when magpie has nothing to fill in.
func SecurityTxt(host string, existingBody []byte, now time.Time) string {
	var fields map[string][]string
	if len(existingBody) > 0 {
		fields = validate.ParseSecurityTxtFields(existingBody)
	}

	var b strings.Builder
	b.WriteString("# Generated by magpie --fix. Review before publishing at\n")
	b.WriteString("# /.well-known/security.txt. Lines marked TODO were not discovered\n")
	b.WriteString("# automatically and need a human decision.\n\n")

	contacts := fields["Contact"]
	if len(contacts) == 0 {
		b.WriteString("# TODO: magpie could not discover a contact method; verify this address.\n")
		contacts = []string{"mailto:security@" + host}
	}
	for _, c := range contacts {
		fmt.Fprintf(&b, "Contact: %s\n", c)
	}

	expires := now.UTC().Add(OneYear).Truncate(time.Second)
	fmt.Fprintf(&b, "Expires: %s\n", expires.Format(time.RFC3339))

	fmt.Fprintf(&b, "Canonical: https://%s/.well-known/security.txt\n", host)

	if enc := firstValue(fields["Encryption"]); enc != "" {
		fmt.Fprintf(&b, "Encryption: %s\n", enc)
	} else {
		b.WriteString("# TODO: add an Encryption field pointing at a PGP key, if you publish one.\n")
	}

	if pol := firstValue(fields["Policy"]); pol != "" {
		fmt.Fprintf(&b, "Policy: %s\n", pol)
	} else {
		b.WriteString("# TODO: add a Policy field describing scope and safe harbor.\n")
	}

	if pl := firstValue(fields["Preferred-Languages"]); pl != "" {
		fmt.Fprintf(&b, "Preferred-Languages: %s\n", pl)
	} else {
		b.WriteString("# TODO: add a Preferred-Languages field, e.g. \"en\".\n")
	}

	if ack := firstValue(fields["Acknowledgments"]); ack != "" {
		fmt.Fprintf(&b, "Acknowledgments: %s\n", ack)
	}
	if hire := firstValue(fields["Hiring"]); hire != "" {
		fmt.Fprintf(&b, "Hiring: %s\n", hire)
	}

	return b.String()
}

func firstValue(vals []string) string {
	if len(vals) == 0 {
		return ""
	}
	return vals[0]
}
